export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_MOVIE_DETAILS = "SET_MOVIE_DETAILS";
export const SET_SEARCHED_MOVIES = "SET_SEARCHED_MOVIES";
